language: r
cache: packages
warnings_are_errors: false

r:
 - oldrel
 - release
 - devel

notifications:
 email:
  on_success: change
  on_failure: change

## dependencies that need to be installed
sudo: true
before_install:
 - sudo apt-get install libpoppler-cpp-dev

# codecov
r_packages:
  - covr

# report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
